Artifcial Intelligence - Project 2
internship project at DECODEABS

Role : Artificial Intelligence Engineer Intern
Task: Data Classification Using AI (Supervised Learning - KNN)
Dataset: Iris Benchmark Dataset
Track: Industrial Training Kit (Batch 2026)

In [2]:
import numpy as np


In [3]:
import pandas as pd

In [4]:
from sklearn.datasets import load_iris

In [5]:
iris = load_iris()

In [6]:
from pandas.io import xml
X= iris.data
Y=iris.target

df = pd.DataFrame(data=X , columns=iris.feature_names)
df['target class'] = Y


print(f"total samples {len(df)} (Balanced:50 per class)")
print(f"Dataset feature (Dimensions) : {iris.feature_names}\n")
print("FIRST FIVE ROWS")
print(df.head())

total samples 150 (Balanced:50 per class)
Dataset feature (Dimensions) : ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

FIRST FIVE ROWS
   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target class  
0             0  
1             0  
2             0  
3             0  
4             0  


In [7]:
from sklearn.model_selection import train_test_split
X_train , X_test , Y_train , Y_test  =  train_test_split(
    X,Y,
    test_size=0.2,
    random_state=42,
    stratify=Y
)
print(f"Training set sizee : {len(X_train)} samples")
print(f"Testing set size (Validation: {len(Y_test)} samples)")

Training set sizee : 120 samples
Testing set size (Validation: 30 samples)


In [8]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("RAW TRAINING SAMPLE")
print(X_train[0])
print("\n STANDARD SCALED TRAINING SAMPLE")
print(X_train_scaled[0])

RAW TRAINING SAMPLE
[4.4 2.9 1.4 0.2]

 STANDARD SCALED TRAINING SAMPLE
[-1.72156775 -0.33210111 -1.34572231 -1.32327558]


In [9]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=5)
model.fit(X_train_scaled, Y_train)
predictions = model.predict(X_test_scaled)

print("Model training complete! Predictions generated for the hidden test set.")

Model training complete! Predictions generated for the hidden test set.


In [11]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
accuracy = accuracy_score(Y_test, predictions)
print(f"Overall Model Accuracy: {accuracy * 100:.2f}%\n")
print(" CONFUSION MATRIX LAYOUT ")
cm = confusion_matrix(Y_test, predictions)
print(cm)

print("\n STRATEGIC PERFORMANCE REPORT ")
print(classification_report(Y_test, predictions, target_names=iris.target_names))

Overall Model Accuracy: 93.33%

 CONFUSION MATRIX LAYOUT 
[[10  0  0]
 [ 0 10  0]
 [ 0  2  8]]

 STRATEGIC PERFORMANCE REPORT 
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       0.83      1.00      0.91        10
   virginica       1.00      0.80      0.89        10

    accuracy                           0.93        30
   macro avg       0.94      0.93      0.93        30
weighted avg       0.94      0.93      0.93        30



In [12]:
!git init

hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint: 
hint: 	git config --global init.defaultBranch <name>
hint: 
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint: 
hint: 	git branch -m <name>
Initialized empty Git repository in /content/.git/
